services:
  mysql:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  api-gateway:
    build: ./api-gateway
    ports:
      - "${API_GATEWAY_HOST_PORT}:8080"
    environment:
      JWT_SECRET: "${JWT_SECRET}" 
    networks:
      - backend
    entrypoint: ["java", "-jar", "app.jar"]

  auth-service:
    build: ./auth-service
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/${AUTH_DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci"
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      JWT_SECRET: "${JWT_SECRET}"
      JWT_EXPIRATION: "${JWT_EXPIRATION}"
      SPRING_MAIL_HOST: "smtp.gmail.com"
      SPRING_MAIL_PORT: "587"
      SPRING_MAIL_USERNAME: "${MAIL_USERNAME}"
      SPRING_MAIL_PASSWORD: "${MAIL_PASSWORD}"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
    entrypoint: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "app.jar"]

  product-service:
    build: ./product-service
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/${PRODUCT_DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci"
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
    entrypoint: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "app.jar"]

  category-service:
    build: ./category-service
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/${CATEGORY_DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci"
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
    entrypoint: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "app.jar"]

  supplier-service:
    build: ./supplier-service
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/${SUPPLIER_DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci"
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
    entrypoint: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "app.jar"]

  brand-service:
    build: ./brand-service
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/${BRAND_DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci"
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
    entrypoint: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "app.jar"]

  upload-service:
    build: ./upload-service
    environment:
      CLOUDINARY_URL: "${CLOUDINARY_URL}"
    networks:
      - backend
    entrypoint: ["java", "-jar", "app.jar"]

volumes:
  mysql_data:

networks:
  backend: