services:
  mysql:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  product-service:
    build: ./product-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/product_service_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_LOGGING_PATTERN_CONSOLE: "%d{HH:mm:ss} %-5level %logger{36} %msg%n"
      SERVER_PORT: "8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
    entrypoint: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "app.jar"]

  category-service:
    build: ./category-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/category_service_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_LOGGING_PATTERN_CONSOLE: "%d{HH:mm:ss} %-5level %logger{36} %msg%n"
      SERVER_PORT: "8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
    entrypoint: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "app.jar"]

  supplier-service:
    build: ./supplier-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/supplier_service_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_LOGGING_PATTERN_CONSOLE: "%d{HH:mm:ss} %-5level %logger{36} %msg%n"
      SERVER_PORT: "8082"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
    entrypoint: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "app.jar"]

  brand-service:
    build: ./brand-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/brand_service_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_LOGGING_PATTERN_CONSOLE: "%d{HH:mm:ss} %-5level %logger{36} %msg%n"
      SERVER_PORT: "8083"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
    entrypoint: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "app.jar"]

  auth-service:
    build: ./auth-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/auth_service_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_LOGGING_PATTERN_CONSOLE: "%d{HH:mm:ss} %-5level %logger{36} %msg%n"
      SERVER_PORT: "8084"
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      JWT_SECRET: "${JWT_SECRET}"
      JWT_EXPIRATION: "${JWT_EXPIRATION}"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
    entrypoint: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "app.jar"]

volumes:
  mysql_data:

networks:
  backend: