server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:

        - id: auth_route
          uri: http://auth-service:8080
          predicates:
            - Path=/auth/**

        - id: product_route
          uri: http://product-service:8080
          predicates:
            - Path=/products/**

        - id: search_route
          uri: http://product-service:8080
          predicates:
            - Path=/search/**

        - id: inventory_route
          uri: http://product-service:8080
          predicates:
            - Path=/inventory/**

        - id: category_route
          uri: http://category-service:8080
          predicates:
            - Path=/categories/**

        - id: supplier_route
          uri: http://supplier-service:8080
          predicates:
            - Path=/suppliers/**

        - id: brand_route
          uri: http://brand-service:8080
          predicates:
            - Path=/brands/**

        - id: upload_route
          uri: http://upload-service:8080
          predicates:
            - Path=/upload/**

        - id: cart_route
          uri: http://cart-service:8080
          predicates:
            - Path=/cart/**

        - id: profile_route
          uri: http://profile-service:8080
          predicates:
            - Path=/profiles/**

        - id: order_route
          uri: http://order-service:8080
          predicates:
            - Path=/orders/**

        - id: payment_route
          uri: http://order-service:8080
          predicates:
            - Path=/vnpay/**

        - id: ai_route
          uri: http://ai-service:8080
          predicates:
            - Path=/ai/**

        - id: recommend_route
          uri: http://recommend-service:5000
          predicates:
            - Path=/recommend/**